# Model fitting

In [1]:
%load_ext autoreload
%autoreload 2

In [7]:
import numpy as np

from neural_clustering.model import dpmm, gmm, util
from neural_clustering import config

In [3]:
import logging
logging.basicConfig(level=logging.INFO)

## Generate toy dataset

In [8]:
cfg = config.load('../config.yaml')
x_train = util.build_toy_dataset(500)

INFO:neural_clustering.model.util:Generated data from two bi-variate normals std=1 (diagonal), mu1 = [5, 5], mu2=[-5, -5]


# DPMM

In [13]:
dpmm.fit(x_train, truncation_level=2, cfg=cfg,
         inference_params=dict(n_iter=500))

  5/500 [  1%]                                ETA: 255s | Loss: nan Inferred cluster means:
[[ 0.25929037  0.05501892]
 [ 0.30143985  0.2669673 ]]
Beta
[ 1.04113793]
 10/500 [  2%]                                ETA: 146s | Loss: nanInferred cluster means:
[[ 0.35581899  0.18861894]
 [ 0.21921922  0.57600772]]
Beta
[ 0.85057271]
 15/500 [  3%]                                ETA: 104s | Loss: nanInferred cluster means:
[[ 0.55738252  0.37784922]
 [-0.0205981   0.55480391]]
Beta
[ 0.80051398]
 20/500 [  4%] █                              ETA: 83s | Loss: nan Inferred cluster means:
[[ 0.7036196   0.4892686 ]
 [-0.15357113  0.5264864 ]]
Beta
[ 0.78712958]
 25/500 [  5%] █                              ETA: 71s | Loss: nanInferred cluster means:
[[ 0.74569881  0.56733352]
 [-0.29177734  0.63715923]]
Beta
[ 0.72519493]
 30/500 [  6%] █                              ETA: 62s | Loss: nanInferred cluster means:
[[ 0.81561613  0.59048641]
 [-0.50561446  0.86219823]]
Beta
[ 0.61913514]
 35/500 [  

255/500 [ 51%] ███████████████                ETA: 15s | Loss: nanInferred cluster means:
[[-0.12775311  0.96692145]
 [-1.66285682  0.77198631]]
Beta
[ 1.04437411]
260/500 [ 52%] ███████████████                ETA: 14s | Loss: nanInferred cluster means:
[[-0.17213236  0.97928435]
 [-1.69305718  0.8591013 ]]
Beta
[ 1.07577574]
265/500 [ 53%] ███████████████                ETA: 14s | Loss: nanInferred cluster means:
[[-0.19493335  0.99201035]
 [-1.58538008  1.07188106]]
Beta
[ 1.10775006]
270/500 [ 54%] ████████████████               ETA: 14s | Loss: nanInferred cluster means:
[[-0.20359918  1.00002682]
 [-1.36493802  1.22133338]]
Beta
[ 1.12568164]
275/500 [ 55%] ████████████████               ETA: 13s | Loss: nanInferred cluster means:
[[-0.23107736  0.98760819]
 [-1.21202159  1.31018734]]
Beta
[ 1.11686349]
280/500 [ 56%] ████████████████               ETA: 13s | Loss: nanInferred cluster means:
[[-0.3615368   0.9117977 ]
 [-1.05406904  1.28960061]]
Beta
[ 1.0938288]
285/500 [ 56%] ██

INFO:neural_clustering.model.dpmm:Session saved in /Users/Edu/data/neural-clustering-toy/sessions/28-Nov-2017@22-51-07-DPMM/session.ckpt
INFO:neural_clustering.model.dpmm:Training data saved in /Users/Edu/data/neural-clustering-toy/sessions/28-Nov-2017@22-51-07-DPMM/training.npy
INFO:neural_clustering.model.dpmm:Params saved in /Users/Edu/data/neural-clustering-toy/sessions/28-Nov-2017@22-51-07-DPMM/params.yaml


# GMM

In [6]:
gmm.fit(x_train, k=2, cfg=cfg, samples=1000)

1000/1000 [100%] ██████████████████████████████ Elapsed: 9s | Acceptance Rate: 1.000


INFO:neural_clustering.model.gmm:Session saved in /Users/Edu/data/neural-clustering-toy/sessions/28-Nov-2017@17-32-31-GMM/session.ckpt
INFO:neural_clustering.model.gmm:Training data saved in /Users/Edu/data/neural-clustering-toy/sessions/28-Nov-2017@17-32-31-GMM/training.npy
INFO:neural_clustering.model.gmm:Params saved in /Users/Edu/data/neural-clustering-toy/sessions/28-Nov-2017@17-32-31-GMM/params.yaml
